### ISSUE TITLE
Trouble installing when `jupyter_client` version `5.2.0` present

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/jupyter_nbextensions_configurator-feedstock#21]
Ran into this issue with `jupyter_client` version `5.2.0` and the latest `jupyter_nbextensions_configurator`. The issue went away with `jupyter_client` version `5.1.0`. The suggestion provided was to build this package with `pip` instead.

```python
jupyter-nbextensions_configurator enable --sys-prefix
Traceback (most recent call last):
  File "/opt/conda3/bin/jupyter-nbextensions_configurator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and is required by jupyter-client
```

xref: https://github.com/conda-forge/jupyter_client-feedstock/pull/14#issuecomment-352510987

**Comment by jcb91** [comment]
Thanks for this @jakirkham!
